name: import

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - id: import
        uses: ega4432/notion-to-markdown-action@v0
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        with:
          # Optional
          output_path: src/content/blog
          filename_property: slug # default: title
      # You can check output files count
      - run: |
          echo "Exported count: ${{ steps.import.outputs.files_count }}
