name: import

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - id: import
        uses: ega4432/notion-to-markdown-action@v0
        env:
          NOTION_API_KEY: ${{ secret_H9VBa4Iplf000w4ikzYlOvO4dlGlDiiAxZgEM2kvOxl }}
          NOTION_DATABASE_ID: ${{ 51dd368eefaf424abc724963ecb99465 }}
        with:
          # Optional
          output_path: some-dir # default: output
          filename_property: slug # default: title
      # You can check output files count
      - run: |
          echo "Exported count: ${{ steps.import.outputs.files_count }}
